# Moving Box Problem

In [1]:
from mdp import *
from moving_box import *

In [2]:
#env = MovingBoxProblem(art_num_states=[20, 20])
#env = MovingBoxProblem(art_sizes=[80, 40, 120], art_num_states=[9, 19, 3], art_angle_limits=[[-30,+30], [-150,0], [-100,+100]])
#env = MovingBoxProblem(body_height=40, body_width=10)
env = MovingBoxProblem(art_num_states=[2, 2])

P = env.getTransitionModel()
print(P)

R = env.getRewardModel()
print(R)

[[0 1 0 1]
 [2 3 2 3]
 [0 0 2 2]
 [1 1 3 3]]
[[  0.           0.           0.          -0.29984565]
 [  0.           0.29984565   0.           0.        ]
 [  0.          37.62035372   0.           0.        ]
 [-37.62035372   0.           0.           0.        ]]


In [3]:
agent = PolicyIterationAgent(env)
print(agent.policy)

policy iterations: 5 ; evaluate iterations: 5
[1 2 3 0]


In [4]:
# object of class Tk, responsible for creating a tkinter toplevel window
viewer = MovingBoxViewer(problem=env, agent=agent)


In [5]:
env.reset()
agent = RandomAgent(env)
viewer = MovingBoxViewer(problem=env, agent=agent)

In [10]:
env.reset()
agent = QLearningAgent(env, epsilon=0.1, alpha=0.1)

for _ in range(1000000):
    agent.act()
agent.epsilon = 0

viewer = MovingBoxViewer(problem=env, agent=agent)

In [12]:
print(np.round(agent.q_values[:], 2))
print(np.argmax(agent.q_values[:], axis=1))
print([env.to_art_action(v) for v in np.argmax(agent.q_values[:], axis=1)])
print(agent.policy)

[[ 1.29  1.38 -3.79 -4.26]
 [16.32 13.95 10.72  1.5 ]
 [ 1.37  1.38  1.38  0.  ]
 [16.29  9.47  6.39  0.  ]]
[1 0 1 0]
[[1, 0], [-1, 0], [1, 0], [-1, 0]]


AttributeError: 'QLearningAgent' object has no attribute 'policy'